spring:
  datasource:
    #   数据源基本配置
    username: zhaowdzxc
    password: Scarlzxc123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf65w117k4w6i8zpeno.mysql.rds.aliyuncs.com:3306/gpu?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
  # redis服务器地址（默认为loaclhost）
    host: 127.0.0.1
  # redis端口（默认为6379）
    port: 6379
  # redis访问密码（默认为空）
    password:
  # redis连接超时时间（单位毫秒）
    timeout: 5000
  # redis连接池配置

  mail:
    host: smtp.163.com
    port: 465
    username: gpumanage@163.com
    password: RSFXNIZLEDVEFUBE
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true